### ISSUE TITLE
Osc.Types causes conflict with Ocaml toploop.cmi

### ISSUE THREAD

**Issue by casperschipper** [johnelse/ocaml-osc#14]
I just tried to run this libraries' example in utop, but I hit an error when I try to load the library:

    #require "osc";;
returns the following error:

    The files ~/.opam/default/lib/osc/osc.cma
    and /usr/local/lib/ocaml/compiler-libs/toploop.cmi
    disagree over interface Types

I am still learning Ocaml, perhaps I am doing something wrong? Or is this really a naming conflict?

**Comment by johnelse** [comment]
Hey Casper, thanks for the report!

What version of `osc` do you have installed, or are you building from source? I'm not able to reproduce your issue - with version 0.1.4 (the latest release) the `Types` module should be contained within a module `Osc`, so shouldn't conflict with the other `Types` module.

For a while the library did export a top level `Types` module, but I believe that was fixed by commit df35053.

**Comment by casperschipper** [comment]
Hi John, thanks for the help! I think I discovered the reason, though my version of ocaml-osc in opam is 0.1.4, I discovered that utop is using the older 0.1.0, so that explains why I see the old problem. Will do some cleanup.
